#!/usr/bin/env bash
# base from http://mrtango.planetcrazy.de/dynamic-screen-definitions-in-i3wm.html
#
# Note this script's stdout will be set as i3 config file!
#####################################

readonly SELF=${0##*/}   # (same as running `basename $0`)
source /etc/.global-bash-init || exit 1
###############


#### Entry ####
echo -e "# vim:filetype=i3\n#\n# auto-generated by ${SELF} {"
echo "set \$hostname $HOSTNAME"
xrandr --listactivemonitors | awk '$1 ~ /^0/ {print "set $mainscreen " $4}'
xrandr --listactivemonitors | awk '$1 ~ /^1/ {print "set $sidescreen " $4}'
echo '# }'

exit 0

