#!/bin/bash
#
# Post-commit git hook script.
#######################
readonly SELF="${0##*/}"

# env vars import has to be the first thing:
if [[ "$__ENV_VARS_LOADED_MARKER_VAR" != "loaded" ]]; then
    SHELL_ENVS=/etc/.bash_env_vars

    if [[ -r "$SHELL_ENVS" ]]; then
        source "$SHELL_ENVS"
    else
        echo -e "\nError: env vars file [$SHELL_ENVS] not found! Abort."
        exit 1
    fi
fi

# import common:
if ! type __COMMONS_LOADED_MARKER > /dev/null 2>&1; then
    if [[ -r "$_SCRIPTS_COMMONS" ]]; then
        source "$_SCRIPTS_COMMONS"
    else
        echo -e "\nError: common file [$_SCRIPTS_COMMONS] not found! Abort."
        exit 1
    fi
fi
# =========================


if is_work; then
    is_function generate_jira_commit_comment || { err_display "can't generate commit msg as dependency is missing" "$SELF"; exit 1; }
    generate_jira_commit_comment && exit 0 || exit 1
fi

