[containers]
# see https://www.redhat.com/en/blog/rootless-podman-user-namespace-modes
userns = "keep-id"

# if we want to change away from default pasta network backend:
#[network]
#default_rootless_network_cmd = "slirp4netns"
