# Search these registries when pulling short names
unqualified-search-registries = ["docker.io", "quay.io", "ghcr.io"]

#[[registry]]
#location = "docker.io"
#blocked = true  # Block public hub for security
