# Search these registries when pulling short names
unqualified-search-registries = ["docker.io", "quay.io", "ghcr.io"]

# Configure a private registry
[[registry]]
location = "registry.example.com"
insecure = false
