---
ruler_x: 0
ruler_y: 522
ruler_length: 2556
track_mouse: true
metric: 5
keep_above: true
foreground_color: "#202020202020"
background_color: "#e6e6e3e36b6b"
font: Sans 12
opacity: 0.85
use_custom_pixels_per_inch: false
horizontal_pixels_per_inch: 96.26632522407171
vertical_pixels_per_inch: 96.26632522407171
