#!/usr/bin/env bash
#
# from https://github.com/anufrievroman/neomutt-file-picker/blob/master/filepicker

# note tempfile is referenced from muttrc macro, so cannot be randomized!
#tmpfile=$HOME/.config/mutt/.picker.tmp
tmpfile=/tmp/.mutt-file-picker.tmp

if \[ -z "$1" \]; then
    #ranger --choosefiles $tmpfile &&    # Use Ranger
    vifm --choose-files "$tmpfile" &&       # Use Vifm
    # yazi "$@" --chooser-file="$tmpfile" && # Use Yazi
    sed --follow-symlinks -i 's/ /^V /g' "$tmpfile" &&
    awk 'BEGIN {printf "%s", "push "} {printf "%s", "<attach-file>\""$0"\"<enter>"}' "$tmpfile" >| "$tmpfile"
elif \[ "$1" == clean \]; then
    rm -- "$tmpfile"
fi
